Strings Format: Use context as key
GlotPress/GlotPress-WP pull request #1105
Opened 2020-05-01 12:19 UTC by akirk

When importing from a .strings file we read the lines as follows (which is correct):

```
/* $comment */
"$context" = "$singular";
```

But when exporting, we export like this:
```
/* $comment */
"$singular" = "$translation";
```

This patch fixes this inconsistency.

2020-05-01 12:45 UTC, ocean90 requested changes
Thanks @akirk! I guess this wasn't noticed because in [our test file](https://github.com/GlotPress/GlotPress-WP/blob/develop/tests/phpunit/data/originals.strings) the original and context is always the same? Can we add one which covers this issue?

2020-05-01 12:45 UTC, ocean90 commented on gp-includes/formats/format-strings.php
> +			$context    = str_replace( "\n", "\\n", $this->escape( $entry->context ) );
```suggestion
			$context     = str_replace( "\n", "\\n", $this->escape( $entry->context ) );
```

2020-05-01 16:02 UTC, merged

2020-11-25 18:42 UTC, AliSoftware commented
Hello @akirk @ocean90 👋  It seems that this PR had the unfortunate consequence of reintroducing #921 – which was fixed by #922 back then, and is where the use of the singular for the key instead of context was introduced.

As a matter of fact, I recently encountered the issue mentioned in #921 (and it took me a while to understand why I had it given that I found #922 that was supposed to have fixed it) for one of our keys that is longer than 255 characters.

2021-01-04 08:22 UTC, akirk commented
Please take a look at [my response on that ticket](https://github.com/GlotPress/GlotPress-WP/issues/921#issuecomment-753828220). Short version is: there is no need to use the English text as a context, you can use anything shorter, you just need to specify an "English translation."