Add short-circuit hook in GP_Original::closest_original.
GlotPress/GlotPress-WP pull request #1207
Opened 2020-11-24 06:47 UTC by gedex

Fixes #1204.

2020-11-24 23:55 UTC, rcstr submitted a review, later dismissed

2020-11-25 14:04 UTC, ocean90 requested changes
Thanks for the pull request! Let's clarify the supported types and update the @since tag.

2020-11-25 14:04 UTC, ocean90 commented on gp-includes/things/original.php
> +		 * @since x.y.z
```suggestion
		 * @since 3.0.0
```

2020-11-25 14:04 UTC, ocean90 commented on gp-includes/things/original.php
> +		 *                              check. Default false.
```suggestion
		 * @param string|false|null  $pre A preemptive return value of closest original
		 *                                check. Default false.
```

2020-11-25 14:04 UTC, ocean90 commented on gp-includes/things/original.php
> +		 * @param array  $other_strings List of string to check against input string.
```suggestion
		 * @param array  $other_strings List of strings to check against input string.
```

2020-12-02 13:13 UTC, gedex commented
Thanks for the feedback, @ocean90.

2021-01-24 14:57 UTC, merged