Add support for the placeholders with precision
GlotPress/GlotPress-WP pull request #1271
Opened 2021-10-14 16:39 UTC by amieiro

Add support for the placeholders with a format like %1$.2f

See https://meta.trac.wordpress.org/ticket/5927

2021-10-14 17:11 UTC, ocean90 requested changes

2021-10-14 17:11 UTC, ocean90 commented on tests/phpunit/testcases/test_builtin_warnings.php
> +		'Extra %1$.4f placeholder in translation.');
Can you make sure these lines use the same code style as the following lines?

2021-10-14 18:13 UTC, amieiro commented on tests/phpunit/testcases/test_builtin_warnings.php
> +		'Extra %1$.4f placeholder in translation.');
Updated.

2021-10-14 19:46 UTC, ocean90 commented on tests/phpunit/testcases/test_builtin_warnings.php
> +		'Extra %1$.4f placeholder in translation.');
Still doesn't look right: https://github.com/GlotPress/GlotPress-WP/blob/8a91ee7d9fb9c39359d6d8d09ace3868efa4221a/tests/phpunit/testcases/test_builtin_warnings.php#L208-L224

2021-10-14 20:08 UTC, amieiro commented on tests/phpunit/testcases/test_builtin_warnings.php
> +		'Extra %1$.4f placeholder in translation.');
Sorry. As I use PhpStorm with parameter name hints enabled, I didn't see this difference. I will update soon. 

![image](https://user-images.githubusercontent.com/1667814/137387584-93e64016-9c5d-48a0-bf10-00b9d878fe08.png)

2021-10-18 12:24 UTC, ocean90 requested changes

2021-10-18 12:24 UTC, ocean90 commented on tests/phpunit/testcases/test_builtin_warnings.php
> +			'Missing %1$.2f placeholder in translation.');
```suggestion
			'Missing %1$.2f placeholder in translation.'
		);
```

2021-10-18 12:24 UTC, ocean90 commented on tests/phpunit/testcases/test_builtin_warnings.php
> +			'Extra %1$.4f placeholder in translation.');
```suggestion
			'Extra %1$.4f placeholder in translation.'
		);
```

2021-10-18 20:02 UTC, merged