Add JavaScript linting
GlotPress/GlotPress-WP pull request #1281
Opened 2021-10-20 16:00 UTC by pedro-mendonca

This is ~WIP~ finished.

Related to #1280 

- [x] Add linting script and GitHub action
- [x] Prepare ruleset with current errors related rules set to off
- [x] Re-enable rules
- [x] Fix JS coding standards

All rules implemented.

2021-10-20 16:46 UTC, pedro-mendonca commented
@ocean90 can you please guide me through some of the next rules that I've muted?

Not sure if should continue to re-enable all of the muted checks.

I think we could at least turn them to "warn".

2021-10-20 17:10 UTC, ocean90 commented on .eslintrc.json
> +  "extends": [ "plugin:@wordpress/eslint-plugin/recommended-with-formatting" ],
This seems to be the wrong config for this project since we are not using ESNext/React. For the start we should only use [es5](https://github.com/WordPress/gutenberg/blob/1e17b5a5b4a3117e843dde015c128361c5ae059e/packages/eslint-plugin/configs/es5.js). Can you change this to see which current disabled rules we can remove?

2021-10-20 17:30 UTC, pedro-mendonca commented on .eslintrc.json
> +  "extends": [ "plugin:@wordpress/eslint-plugin/recommended-with-formatting" ],
If I add only the *es5* the *i18n* is left out, should we add it also?

2021-10-20 17:45 UTC, pedro-mendonca commented on .eslintrc.json
> +  "extends": [ "plugin:@wordpress/eslint-plugin/recommended-with-formatting" ],
@ocean90  After applying this `es5` I see that the only rule I've fixed above that is not necessary on `es5` is the "computed-property-spacing". I can safely revert the fix on https://github.com/GlotPress/GlotPress-WP/pull/1281/commits/47743c8e0b9b764db613e7a03fa2b64e7d9a0e95

2021-10-20 18:34 UTC, ocean90 commented on .eslintrc.json
> +  "extends": [ "plugin:@wordpress/eslint-plugin/recommended-with-formatting" ],
`i18n` is only relevant if we use [`wp.i18n`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-i18n/). Since we don't we can safely ignore that for now.

> that is not necessary on `es5` is the "computed-property-spacing"

That's interesting since it's not really ESNext specific… Let's keep that and copy the custom rule for it:

```
'computed-property-spacing': [ 'error', 'always' ],
```

2021-10-20 22:12 UTC, pedro-mendonca commented on .eslintrc.json
> +  "extends": [ "plugin:@wordpress/eslint-plugin/recommended-with-formatting" ],
Done

2021-10-21 08:14 UTC, pedro-mendonca commented
@ocean90 from now I'll follow the example of the existent page top jscs comments and keep the matching exceptions.
After this, I think we can delete the jscs related files, right?

2021-10-23 12:15 UTC, ocean90 requested changes
To fix `'data' is already declared in the upper scope` we could rename the argument in the `success()` callback to `response`.

2021-10-23 12:15 UTC, ocean90 commented on assets/js/common.js
> +			var options = $.extend( {}, defaults, options );
You can fix this by renaming the `options` argument to `userOptions`, `defaults` to `defaultOptions` and then use 

```suggestion
			var options = $.extend( {}, defaultOptions, userOptions );
```

2021-10-23 18:35 UTC, pedro-mendonca commented on assets/js/common.js
> +			var options = $.extend( {}, defaults, options );
"no-redeclare" fixed in https://github.com/GlotPress/GlotPress-WP/pull/1281/commits/834db775f2f19b83c38c4aae4b0438d096ea60bb

2021-10-23 18:42 UTC, pedro-mendonca commented on assets/js/common.js
> +			var options = $.extend( {}, defaults, options );
"no-shadow" fixed in https://github.com/GlotPress/GlotPress-WP/pull/1281/commits/125d7aab04747254c48777d4d9cbfe2a04cb8307

2021-10-25 18:39 UTC, ocean90 approved these changes

2021-10-25 18:57 UTC, ocean90 commented
@pedro-mendonca Since the title still includes WIP, is there anything left here or is good to merge?

2021-10-25 19:08 UTC, pedro-mendonca commented
@ocean90 it's done, I'm renaming it now.

2021-10-25 19:21 UTC, merged

2021-11-02 21:47 UTC, pedro-mendonca commented
@ocean90 are the below files still necessary?

- .jscsrc
- .jshintignore
- .jshintrc