1376: Add CSS to current navigation menu item
GlotPress/GlotPress-WP pull request #1379
Opened 2022-04-01 12:57 UTC by pedro-mendonca

This allows to clearly identify the active navigation menu item.

Fixes #1376

2022-04-01 15:43 UTC, ocean90 reviewed
I'd prefer something more subtle here. Maybe `box-shadow: inset 0 -5px 0 var( --gp-color-secondary-900 )` and change to white on hover instead of current text underline?

<img width="352" alt="image" src="https://user-images.githubusercontent.com/617637/161297008-f3872247-81d3-4ed8-aeee-bf876b3cf931.png">

2022-04-01 15:53 UTC, pedro-mendonca commented
@ocean90 it has too low contrast, hardly noted.

2022-04-20 10:55 UTC, pedro-mendonca commented
Below are a few possible navbar solutions.

These examples have the **Projects** as the `.current` item, and the **Profile** is the `:hover`/`:focus` status.

1. The current PR status
![imagem](https://user-images.githubusercontent.com/7371591/164214170-d96a95fe-e85a-4a0a-8014-d3ed02f9f173.png)

2. The @ocean90 suggestion on [this comment](https://github.com/GlotPress/GlotPress/pull/1379#pullrequestreview-929119385)
![imagem](https://user-images.githubusercontent.com/7371591/164214277-fe6c59eb-0d20-41e6-a3e7-8e570b22696c.png)

3. A third option, using the below box-shadow but with higher contrast on `.current` and using the glotpress `--gp-color-primary` variations.
![imagem](https://user-images.githubusercontent.com/7371591/164214391-d448485b-416e-4c9e-96ef-c1e70acf75a2.png)


Please give feedback.

2022-04-20 12:47 UTC, amieiro commented
In my opinion, the third option is the best: it is subtle, but it has more contrast than if you use gray or white.

2022-04-20 19:59 UTC, ocean90 requested changes
Using the primary color as an underline for the current item sounds good too. But there's no need to use different colors for the left and right menu, they can use the same colors to keep it simple.

2022-04-20 19:59 UTC, ocean90 commented on gp-includes/template.php
> +	$current_uri = gp_url( $gp_route );
You can use `gp_url_current()` here.

2022-04-20 19:59 UTC, ocean90 commented on gp-includes/template.php
> +		$class = str_starts_with( $current_uri, $link ) ? 'current' : '';
`str_starts_with()` is a PHP 8 function and only polyfilled in WordPress 5.9+. You can use `gp_startswith()` instead.

2022-04-20 19:59 UTC, ocean90 commented on gp-templates/header.php
> +		<nav id="home-navigation">
This is not a navigation, let's keep it as h1 for now.

2022-04-22 10:26 UTC, pedro-mendonca commented
@ocean90 As I've mentioned above, the left and right colors show different status, on the left is a primary color to show the current status, and on the right I've placed a primary-color-200 to differentiate on hover on the current item.

2022-04-22 12:36 UTC, pedro-mendonca commented
@ocean90 and @amieiro I've changed to the option 3.

2022-04-22 16:19 UTC, ocean90 approved these changes

2022-04-22 18:55 UTC, merged

2022-04-22 19:18 UTC, pedro-mendonca commented
Thanks for fixing the loose ends :)