1423: Add "Last Modified" column to Glossary
GlotPress/GlotPress-WP pull request #1428
Opened 2022-05-04 13:13 UTC by pedro-mendonca

This PR already includes the `data-sorter` for tablesorter added on https://github.com/GlotPress/GlotPress/pull/1426

- [x] Add **Last Modified** column to Glossary
- [x] Add `data-sorter` to set as sorteable
- [x] Format data and time both in row and editor

Fixes #1423

2022-07-13 15:07 UTC, pedro-mendonca commented
This PR still requires a build step for the .min.css, should I build and add for review?

2022-09-10 13:29 UTC, ocean90 requested changes
Some minor changes related to date handling.

2022-09-10 13:29 UTC, ocean90 commented on gp-templates/glossary-entry-row.php
> +	$date_modified_formated = sprintf(
```suggestion
	$date_modified           = strtotime( $entry->date_modified );
	$date_modified_formatted = sprintf(
```

2022-09-10 13:29 UTC, ocean90 commented on gp-templates/glossary-entry-row.php
> +		<?php echo esc_html( $date_modified_formated ); ?>
```suggestion
		<?php echo esc_html( $date_modified_formatted ); ?>
```

2022-09-10 13:29 UTC, ocean90 commented on gp-templates/glossary-entry-row.php
> +				<dd><?php echo esc_html( $date_modified_formated ); ?></dd>
```suggestion
				<dd><?php echo esc_html( $date_modified_formatted ); ?></dd>
```

2022-09-10 13:29 UTC, ocean90 commented on gp-templates/glossary-entry-row.php
> +		date_i18n( get_option( 'time_format' ), $date_modified )
```suggestion
		wp_date( get_option( 'date_format' ), $date_modified ),
		wp_date( get_option( 'time_format' ), $date_modified )
```

2022-09-10 23:40 UTC, pedro-mendonca commented
All suggestions applied, done.

2022-09-12 06:37 UTC, ocean90 requested changes

2022-09-12 06:37 UTC, ocean90 commented on gp-templates/glossary-entry-row.php
> +		esc_html__( '%1$s at %2$s', 'glotpress' ),
```suggestion
		__( '%1$s at %2$s', 'glotpress' ),
```

2022-09-12 06:37 UTC, ocean90 approved these changes

2022-09-12 07:42 UTC, merged