Local:Copy placeholder into textarea on click
GlotPress/GlotPress-WP pull request #1596
Opened 2023-03-28 14:07 UTC by trymebytes

## What?

## Why?

## How?

## Testing Instructions

## Screenshots or screencast

2023-04-05 09:01 UTC, akirk requested changes
We should indicate that the placeholders have already been used with a checkmark.

2023-04-05 09:01 UTC, akirk commented on inline-translation/lib/popover.js
> +		transTextarea.val( textBefore + placeholder + textAfter );
We should try to avoid setting the textarea value with `val()` (or `.value=`) and rather use `document.execCommand( 'insertText', null, text )` so that the browser keeps the textarea's undo buffer.

2023-04-05 09:01 UTC, akirk commented on inline-translation/lib/original.js
> +				return '<a class="inline-placeholder" href="#">' + match[ 0 ] + '</a>';
Please add a checkmark if the translation is already used. This means that we need to run this function on keyup.

2023-04-17 11:13 UTC, amieiro requested changes
I have detected some small problems.

## Duplicated placeholders

If the placeholder appears two or more times in the original, we have it duplicated. I think we should remove the duplicates.

![image](https://user-images.githubusercontent.com/1667814/232466496-bf8059fe-20c4-4159-801d-34895e58d731.png)

## Doesn't check on plurals

If the translation has plurals, we need to check the placeholder in the plural.

![image](https://user-images.githubusercontent.com/1667814/232466812-02724a94-485f-4172-92c5-5f1b4f24210d.png)

## Colors 

![image](https://user-images.githubusercontent.com/1667814/232468331-81ca11b2-e069-4a0e-9619-215546369843.png)


Related with [this post](https://make.wordpress.org/polyglots/2022/12/07/color-blindness-in-the-diffs-from-the-translation-memory/), I will recommend you to change the orange to red, because red is identified with some misusage. Currently, we are using #F1ADAD as red and #B5E1B9 as green, but with `text-decoration: line-through;` for the red color, so people with color blindness don't have any problems to understand this.

2023-04-18 09:10 UTC, amieiro commented on inline-translation/css/custom.css
> +	text-decoration: none;
I will suggest you to add a line though to this CSS, so the people with color blindness can differentiate between the existing and non-existing placeholders:
```suggestion
	text-decoration: line-through;
```

2023-04-24 14:42 UTC, amieiro requested changes
Two improvements:

## Duplicated placeholders

If you add the same placeholder twice, because the original string has it twice, you need to mark one as found and the other as not found.

This is the current situation

![image](https://user-images.githubusercontent.com/1667814/234028448-a38967c4-486e-4768-ac6e-43512767abaa.png)

And this is the suggested

![image](https://user-images.githubusercontent.com/1667814/234029127-7b35660f-59f2-4941-9a23-25452484bd30.png)

## Plurals

You need to check the plural translations.

This is the current situation 

![image](https://user-images.githubusercontent.com/1667814/234029642-c7dac635-f437-423f-9839-e7f8d092261a.png)

And this is the suggested:
* space between the placeholders and the next title.
* placeholders in the translation plurals.

![image](https://user-images.githubusercontent.com/1667814/234030778-04c5bf8a-9a48-4489-9ac2-ec87307c47d5.png)

2023-04-25 11:38 UTC, trymebytes commented
Thank you @amieiro. For the plurals, the placeholders are displayed when there's second textarea. I could improve it such that we can display the placeholders before focus on the second textarea
![plural-placeholder](https://user-images.githubusercontent.com/2834132/234264827-450118dc-274c-4610-b81c-31dd6404e415.gif)

2023-05-03 13:12 UTC, akirk requested changes
Warnings were not shown, I committed a fix to this PR. What remains is that the spacing is off and that duplicate placeholders are shown:
<img width="448" alt="Screenshot 2023-05-03 at 15 11 17" src="https://user-images.githubusercontent.com/203408/235926018-3075cbe1-1819-4cfe-8a66-4c55fc2e40c5.png">

2023-05-03 14:30 UTC, trymebytes commented
Thank you @akirk! Regarding the duplicates, the `%1$s` placeholder appears twice in the original and so it appears twice in the list below the textarea, do you suggest that we should only display one in the list of placeholders regardless of the number of occurrence in the original?

2023-05-04 09:36 UTC, akirk commented
I thought about it and I think the current behavior is right indeed. For numbered placeholders, duplicate placeholders can be omitted, but not unnumbered. So let's keep the current behavior.

2023-05-05 06:49 UTC, akirk commented
@trymebytes will you be able to rebase this and fix the styling today?

2023-05-05 15:00 UTC, akirk commented
I tested it and it looks good, merging!

2023-05-05 15:02 UTC, merged