Site tour on translate.wordpress.org
GlotPress/GlotPress-WP pull request #1632
Opened 2023-05-31 23:40 UTC by trymebytes

## What?

## Why?

## How?

## Testing Instructions

## Screenshots or screencast

2023-08-02 09:45 UTC, trymebytes commented
Update: The steps as specified in the tour draft have been added.

![tour-3](https://github.com/GlotPress/GlotPress/assets/2834132/5caecef5-cdbf-40aa-91ee-1aaf2b01cf85)

2023-08-08 13:52 UTC, pedro-mendonca commented
I would like to suggest using a single color for the popover element, e.g. assinging the GlotPress primary color to a new color var: `gp-color-tour`.

It also needs a few tweaks so that the dashed border doesn't change the UI rendering. I'm not sure if it's a good practice, but I've achieved some good results using a negative margin for the `pulse-wrapper`.
To test this, set a Tour with popovers in both Projects links (Create new and Projects per Locale) to see how the UI is currently shifting.

Also, instead of having CSS for Previous and Next, might be useful to use a generic CSS for the popover buttons and a `primary-button` class to highlight the Next.

![imagem](https://github.com/GlotPress/GlotPress/assets/7371591/a2f4aa8e-3b1e-4876-b1f9-cc72318e0b56)
![imagem](https://github.com/GlotPress/GlotPress/assets/7371591/0648ddd9-56e7-4cc5-b254-590334706c7b)
![imagem](https://github.com/GlotPress/GlotPress/assets/7371591/d98deb9f-b5d2-4b30-8235-9ef47666343f)

I'll add a PR for the `site-tour` branch for you to test.

2023-08-08 14:00 UTC, trymebytes commented
Awesome! Thank you so much for the feedback @pedro-mendonca, looking forward to your PR!

2023-09-04 11:49 UTC, trymebytes commented
@pedro-mendonca I cherry picked and applied some of your commits from your [PR](https://github.com/GlotPress/GlotPress/pull/1669) here since that branch has diverged significantly, thank you!

2023-09-15 14:39 UTC, akirk requested changes
You can get stuck on the first step of the tour if the references are missing. While this is technically for https://github.com/WordPress/wordpress.org/pull/172, the tour should be capable of skipping a step if it cannot find the pulse element.

2023-09-18 15:17 UTC, akirk requested changes

2023-09-18 15:17 UTC, akirk commented on assets/js/tour.js
>  						if ( jQuery( window.tour[ tourName ][ nextItem ].selector ).length > 0 ) {
This also needs the selector.

2023-09-18 16:00 UTC, akirk approved these changes
Works now for me!

2023-09-19 13:26 UTC, merged