Resolve a bug with the glossary variations
GlotPress/GlotPress-WP pull request #1706
Opened 2023-09-28 12:25 UTC by amieiro

## Problem

In https://github.com/GlotPress/GlotPress/pull/1696 I introduced a bug with the glossary variations, not detecting them. You can see it in the next screenshot.

![image](https://github.com/GlotPress/GlotPress/assets/1667814/40ea7ac6-5706-4ce4-a255-e2b6ed0efb6e)

## Solution

This PR updates the regular expression that splits the original string with the glossary terms and with the placeholders.

![image](https://github.com/GlotPress/GlotPress/assets/1667814/00a14c7f-5550-4e46-aed5-cb97fd354194)

## Testing Instructions

I have added two new tests to avoid this error another time:
- test_map_glossary_entries_with_variations.
- test_map_glossary_entries_with_variations_and_placeholders.

The load time using [this method](https://github.com/GlotPress/GlotPress/pull/1696#issuecomment-1737029365) is very similar:
- Before PR: Mean load time: 733.000 milliseconds
- After PR. Mean load time: 723.000 millisecond

2023-09-28 12:28 UTC, akirk requested changes
The unit test doesn't test the bug, it passes both with and without the change to `gp-templates/helper-functions.php`.

2023-09-28 12:33 UTC, pedro-mendonca commented
The glossary variations are matched in an enterely different way on https://github.com/GlotPress/GlotPress/pull/1373
Can you check if this problem exists with that code?

2023-09-28 17:08 UTC, amieiro commented
@pedro-mendonca I detected this problem when I was setting up my environment with your [.pot file](https://github.com/pedro-mendonca/GlotPress/blob/glossary-suffix-testing-example/tests/phpunit/data/glossary-suffix-testing-example--originals.pot) and your [glossary CSV](https://github.com/pedro-mendonca/GlotPress/blob/glossary-suffix-testing-example/tests/phpunit/data/glossary-suffix-testing-example--locale-glossary.csv), but with the `develop` branch, so I think it will work in your PR.

### Develop branch

This is the regex using Pedro's glossary

`(%(?:[1-9]\$)?[bcdefgosuxEFGX%l@])|(\b(?:abbreviate|contravene|contribute|authorize|subscribe|supervise|compress|disperse|perceive|abstain|compose|confuse|convert|correct|encrypt|exclaim|exclude|explode|precede|prevent|resolve|decide|delete|emerge|extend|format|ignite|insert|invade|resume|submit|tiptoe|tomato|agree|coach|expel|recur|waltz|watch|care|dish|edit|hero|kiss|lens|make|pass|pull|push|quiz|box|bus|dye|fix|see|do|go)(?:s|es|ed|ing)?|(?:liquef|specif|dela|lad|pla|gu|ke|to|tr)(?:y|ies|ys)?|(?:che|lea|wol)(?:f|ves)?|(?:wom)(?:an|en)?|(?:wi)(?:fe|ves)?\b)`

and this is the matched string, the same that I showed in the first screenshot in this PR:

![image](https://github.com/GlotPress/GlotPress/assets/1667814/52293b65-8377-4da7-8c7a-7104496ba393)

The regex from the unit test `test_map_glossary_entries_with_variations_and_placeholders()`:

`(%(?:[1-9]\$)?[bcdefgosuxEFGX%l@])|(\b(?:convert|see)(?:s|es|ed|ing)?|(?:dela|gu|ke|to)(?:y|ies|ys)?\b)`

and this is the matched string (different from the previous screenshot):

![image](https://github.com/GlotPress/GlotPress/assets/1667814/2f980aea-1917-40c5-a075-b897c797f951)

### This PR

With this PR, this is the regex using Pedro's glossary
 
`(%(?:[1-9]\$)?[bcdefgosuxEFGX%l@])|\b((?:abbreviate|contravene|contribute|authorize|subscribe|supervise|compress|disperse|perceive|abstain|compose|confuse|convert|correct|encrypt|exclaim|exclude|explode|precede|prevent|resolve|decide|delete|emerge|extend|format|ignite|insert|invade|resume|submit|tiptoe|tomato|agree|coach|expel|recur|waltz|watch|care|dish|edit|hero|kiss|lens|make|pass|pull|push|quiz|box|bus|dye|fix|see|do|go)(?:s|es|ed|ing)?|(?:liquef|specif|dela|lad|pla|gu|ke|to|tr)(?:y|ies|ys)?|(?:che|lea|wol)(?:f|ves)?|(?:wom)(?:an|en)?|(?:wi)(?:fe|ves)?)\b`

and this is the matched string, the same that I showed in the second screenshot in this PR:

![image](https://github.com/GlotPress/GlotPress/assets/1667814/ab238c0e-2037-4cb1-805b-b61de91b04f4)

The regex from the unit test `test_map_glossary_entries_with_variations_and_placeholders()`:

`(%(?:[1-9]\$)?[bcdefgosuxEFGX%l@])|\b((?:convert|see)(?:s|es|ed|ing)?|(?:dela|gu|ke|to)(?:y|ies|ys)?)\b`

and this is the matched string:

![image](https://github.com/GlotPress/GlotPress/assets/1667814/7834a455-d77f-46a6-945d-51e64a6c86c1)

This PR is need, because currently the variations are not well managed, but I didn't add enough different items in the glossary to make fail the previous code with the new tests.  I have added a few items to the glossaries in one test, so the previous code will fail with the `test_map_glossary_entries_with_variations_and_placeholders()` test. Good catch @akirk

2023-10-05 13:34 UTC, akirk approved these changes
Tested again, now the unit test covers the change. Thank you!

2023-10-05 13:48 UTC, merged