Use driver.js for site tour
GlotPress/GlotPress-WP pull request #1714
Opened 2023-10-04 22:48 UTC by trymebytes

## Problem
For more flexibilities and out of the box features, we are trying out the driver.js library.

## Solution

Include the driver.js library to power the site tour.

## Screenshots or screencast
![using-driverjs](https://github.com/GlotPress/GlotPress/assets/2834132/4d2a1ce7-0b11-4b06-a085-193e12c09932)

2023-10-05 08:52 UTC, akirk reviewed
Nice, I am surprised how easy it looks to swap it out!

2023-10-05 08:52 UTC, akirk commented on gp-includes/assets-loader.php
> +	wp_register_style( 'driver-js', 'https://cdn.jsdelivr.net/npm/driver.js@1.0.1/dist/driver.css', array(), '1.0.1' );
I think we should be using a local copy, so can you add this file under `assets/css` to the PR and use that?

2023-10-05 08:52 UTC, akirk commented on gp-includes/assets-loader.php
> +	wp_register_script( 'driver-js', 'https://cdn.jsdelivr.net/npm/driver.js@1.0.1/dist/driver.js.iife.js', array(), '1.0.1' );
I think we should be using a local copy, so can you add this file under `assets/js` to the PR and use that?

2023-10-05 09:30 UTC, akirk commented on gp-includes/assets-loader.php
> +	wp_register_script( 'driver-js', 'https://cdn.jsdelivr.net/npm/driver.js@1.0.1/dist/driver.js.iife.js', array(), '1.0.1' );
[The current version is 1.3.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.3.0), maybe we can use that

2023-10-09 11:59 UTC, akirk commented
It works well if I run it on the first string. But things no longer work if I start in the second one. Upon first sight it doesn't appear as if it supported a jQuery like `:visible` selector. Is there anything we can do about it?

2023-10-09 14:19 UTC, amieiro requested changes, later dismissed

2023-10-09 14:19 UTC, amieiro commented on gp-includes/assets-loader.php
> +	wp_register_style( 'driver-js', $url . '/driver-js' . $suffix, array(), '1.3.0' );
Please, change the hard-coded version to a one based in the filemtime:

```suggestion
	wp_register_style( 'driver-js', $url . '/driver-js' . $suffix, array(), filemtime( $path . 'driver-js' . $suffix ) );
```

2023-10-09 14:19 UTC, amieiro commented on gp-includes/assets-loader.php
> +	wp_register_script( 'driver-js', $url . '/driver-js' . $suffix, array(), '1.3.0' );
Please, change the hard-coded version to a one based in the filemtime:

```suggestion
	wp_register_script( 'driver-js', $url . '/driver-js' . $suffix, array(), filemtime( $path . 'driver-js' . $suffix ) );

```

2023-10-11 11:11 UTC, trymebytes commented
Converting this to a draft while I work on the patch to driver.js in a forked repository for easy referencing.

2023-10-13 09:32 UTC, akirk approved these changes
Works well!

2023-10-13 10:54 UTC, merged