Update AZB properties in locales.php
GlotPress/GlotPress-WP pull request #1763
Opened 2024-01-11 13:13 UTC by tobifjellner

Update properties for AZB locale as per request from locale team at https://make.wordpress.org/polyglots/2023/12/24/azb-locale-edit-azb-locale/

Solves https://github.com/GlotPress/GlotPress/issues/1762

2024-01-11 13:54 UTC, trymebytes approved these changes, later dismissed

2024-04-05 07:06 UTC, arazgholami commented
Not agree with changes. Explained in [#1762](https://github.com/GlotPress/GlotPress/issues/1762)

2024-04-05 07:54 UTC, arazgholami requested changes

2024-04-05 07:54 UTC, arazgholami commented on locales/locales.php
> +		$azb->native_name = 'تورکجه (تورکی)';
```suggestion
		$azb->english_name = 'South Azerbaijani';
		$azb->native_name = 'تۆرکجه‌ (آذربایجان تۆرکجه‌سی)';
```

2024-04-05 07:54 UTC, arazgholami commented on locales/locales.php
> +		$azb->native_name = 'تورکجه (تورکی)';
Not agree with changes. Explained in [#1762](https://github.com/GlotPress/GlotPress/issues/1762)

2024-04-24 15:04 UTC, arazgholami approved these changes

2025-06-25 13:14 UTC, amieiro approved these changes

2025-06-25 13:14 UTC, merged