701: Fix entry/display of translations that start with a blank line.
GlotPress/GlotPress-WP pull request #715
Opened 2017-05-09 21:22 UTC by toolstack

Resolves #701.

2017-05-30 21:11 UTC, ocean90 requested changes
Needs an update of the minified file and a version bump.

2017-05-30 21:11 UTC, ocean90 commented on gp-templates/helper-functions.php
> +	if( gp_startswith( $text, "\r\n" ) ) {
Missing whitespace

2017-05-30 21:11 UTC, ocean90 commented on gp-templates/helper-functions.php
> +		if( gp_startswith( $text, "\n" ) ) {
Missing whitespace

2017-05-30 21:11 UTC, ocean90 commented on gp-templates/helper-functions.php
> +function prepare_translation_textarea( $text ) {
Missing `gp_` prefix

2017-05-30 21:11 UTC, ocean90 commented on gp-templates/helper-functions.php
> +		<textarea class="foreign-text" name="translation[<?php echo esc_attr( $entry->original_id ); ?>][]" id="translation_<?php echo esc_attr( $entry->original_id ); ?>_<?php echo esc_attr( $index ); ?>"
Shouldn't this be the other way around? `esc_translation( prepare_translation_textarea( … ) )`

2017-05-30 23:10 UTC, toolstack commented on gp-templates/helper-functions.php
> +function prepare_translation_textarea( $text ) {
Fixed.

2017-05-30 23:11 UTC, toolstack commented on gp-templates/helper-functions.php
> +	if( gp_startswith( $text, "\r\n" ) ) {
Fixed.

2017-05-30 23:12 UTC, toolstack commented on gp-templates/helper-functions.php
> +		if( gp_startswith( $text, "\n" ) ) {
Fixed.

2017-05-30 23:14 UTC, toolstack commented on gp-templates/helper-functions.php
> +		<textarea class="foreign-text" name="translation[<?php echo esc_attr( $entry->original_id ); ?>][]" id="translation_<?php echo esc_attr( $entry->original_id ); ?>_<?php echo esc_attr( $index ); ?>"
Doesn't really matter, I chose this way to make sure the extra `lf` was added as late as possible just in case.

2017-05-30 23:16 UTC, toolstack commented
Bumped asset loader version and the minified file is already included in the PR.

2017-05-30 23:29 UTC, toolstack commented
The blocking conflict is because we've merged another update to the minification file in to develop and of course git can't resolve the issue.  I'll have to rebase the PR.

2017-05-31 00:43 UTC, toolstack commented
PR rebased.

2017-06-06 21:57 UTC, ocean90 approved these changes

2017-06-07 11:01 UTC, merged