237: Add counts to filter links in the translation page.
GlotPress/GlotPress-WP pull request #741
Opened 2017-06-22 21:31 UTC by toolstack

Resolves #237.

2017-06-27 18:07 UTC, ocean90 requested changes
Since we now have the counts, should we hide the links if the count is zero?

2017-06-27 18:07 UTC, ocean90 commented on gp-templates/translations.php
> +		sprintf( __( 'Untranslated&nbsp;[%d]&nbsp;(random)', 'glotpress' ), $translation_set->untranslated_count() )
We should use `number_format_i18n()` for numbers (and `%s` for the placeholder).

2017-06-27 18:07 UTC, ocean90 commented on gp-templates/translations.php
> +		sprintf( __( 'Untranslated&nbsp;[%d]&nbsp;(random)', 'glotpress' ), $translation_set->untranslated_count() )
Random was a separate link.

2017-06-27 21:21 UTC, toolstack commented
I kind of like seeing the zeros, it make it clear there are no fuzzies/waiting/warnings :)

It gives you a sense of accomplishment.

2017-06-28 20:50 UTC, ocean90 approved these changes

2017-06-28 20:51 UTC, merged