745: Check duplicate glossary entries
GlotPress/GlotPress-WP pull request #746
Opened 2017-06-23 22:35 UTC by toolstack

Resolves #745.

2017-06-27 18:30 UTC, ocean90 requested changes

2017-06-27 18:30 UTC, ocean90 commented on gp-includes/routes/glossary-entry.php
> +				'term' => $new_glossary_entry->term,
This should probably also include `$part_of_speech`

2017-06-27 18:30 UTC, ocean90 commented on gp-includes/routes/glossary-entry.php
> +				$this->errors[] = sprintf( __( 'Error "%s" is a duplicate glossary entry!', 'glotpress' ), esc_html( $new_glossary_entry->term ) );
Maybe make that message similar to https://github.com/GlotPress/GlotPress-WP/blob/cb79407aec395b4e3a5f6e0f9b3a79eb91914168/gp-includes/routes/translation.php#L290

2017-06-27 20:29 UTC, toolstack commented on gp-includes/routes/glossary-entry.php
> +				'term' => $new_glossary_entry->term,
Updated.

2017-06-27 20:29 UTC, toolstack commented on gp-includes/routes/glossary-entry.php
> +				$this->errors[] = sprintf( __( 'Error "%s" is a duplicate glossary entry!', 'glotpress' ), esc_html( $new_glossary_entry->term ) );
Updated.

2017-07-02 13:56 UTC, ocean90 approved these changes

2017-07-02 13:56 UTC, merged