226: support locale variants
GlotPress/GlotPress-WP pull request #747
Opened 2017-06-27 21:14 UTC by toolstack

Resolves #266.

2017-07-12 11:12 UTC, swissspidy commented on locales/locales.php
> +		$gsw->variant_root = $de->slug;
Please note that while German (Switzerland) as a variant of standard German makes sense, Swiss German (gsw) is something completely different. It's a dialect (well, more than 26 different dialects to be precise) that has nothing in common with regular German. As such, `$gsw` shouldn't be a variant of `$de`.

2017-07-12 11:28 UTC, pixelverbieger commented on locales/locales.php
> +		$gsw->variant_root = $de->slug;
… while de_DE_formal is missing and could be added to the list of variants for German

2017-07-12 11:37 UTC, swissspidy commented on locales/locales.php
> +		$gsw->variant_root = $de->slug;
That would be handled somewhere else though 🙂 `de_DE_formal` is not listed in `locales.php` after all, it's probably just a WordPress.org thing.

2017-07-12 12:35 UTC, toolstack commented on locales/locales.php
> +		$gsw->variant_root = $de->slug;
Thanks @swissspidy, I'll remove the relationship.

@pixelverbieger I'm sure there will be many new variants added, like de_DE_formal once the the PR is merged, currently swisspidy is correct that the formal variants are handled by translate.w.org separately.

2017-11-23 16:33 UTC, ocean90 requested changes

2017-11-23 16:33 UTC, ocean90 commented on gp-templates/translation-row.php
> +				<dt><?php _e( 'Root Translaton:', 'glotpress' ); ?></dt>
Typo

2017-11-23 23:39 UTC, toolstack commented on gp-templates/translation-row.php
> +				<dt><?php _e( 'Root Translaton:', 'glotpress' ); ?></dt>
Fixed.

2018-04-21 04:38 UTC, HughP commented
I’m not sure why the code invokes iso 629-2 codes.  BCP 47 Tags should be used. 

I don’t have a problem with the fallbacks chosen. They make sense. But it seems that the coding seems more complex than needed. ISO 639-2 and 639-3 are alligned for the purposes of locale codes CLDR or Iana should have the already Approved codes.

2018-10-26 07:55 UTC, xavivars commented
Any idea of progress on this PR? 

While discussing about the details could take forever (this language is/is-not a variant of another language), the functionality itself it's extremely useful for cases that are clear. For example, we now have *Valencian (ca-valencia, Catalan as spoken in Valencia), and falling back to English is simply not an option: there aren't enough translators to keep all themes/plugins up to date in both variants.

2018-10-26 13:04 UTC, toolstack commented
It will be merged as part of 3.0, which is scheduled for a Dec 20th release.

2018-11-28 06:15 UTC, xavivars commented
I guess ca-valencia will need to be added as a variant of ca in locales.php for this case to work, right?

2018-11-28 12:55 UTC, toolstack commented
@xavivars Correct, it can be done for a site by either hooking in to the `gp_locale_definitions_arrary` filter or creating a custom locales file.

2019-01-03 17:32 UTC, merged