Add Maltese to locales.php
GlotPress/GlotPress-WP pull request #761
Opened 2017-06-29 12:48 UTC by tobifjellner

translate.wordpress.org has received a request to add Maltese for translation.

2017-06-29 15:37 UTC, SergeyBiryukov commented
Related request: https://make.wordpress.org/polyglots/2017/06/27/hello-10/
Related Ethnologue information: https://www.ethnologue.com/language/mlt

2017-07-01 20:59 UTC, ocean90 requested changes
Thanks for the PR!

Please take a look at our [contributing guidelines](https://github.com/GlotPress/GlotPress-WP/blob/develop/.github/CONTRIBUTING.md#submitting-patches). They request that you first create an issue like https://github.com/GlotPress/GlotPress-WP/issues/411. Also, commit messages should include more than "Update xyz".

2017-07-01 20:59 UTC, ocean90 commented on locales/locales.php
> +		$mt->plural_expression = '(n==1 ? 0 : n==0 || ( n%100&gt;1 &amp;&amp; n%10010 &amp;&amp; n%100&lt;20 ) ? 2 : 3);';
There's some escaped HTML.

2017-07-01 20:59 UTC, ocean90 commented on locales/locales.php
> +		$mt->slug = 'mt';
The slug should be `mlt`.

2017-07-01 20:59 UTC, ocean90 commented on locales/locales.php
> +		$mt = new GP_Locale();
The variable should be `$mlt`

2017-07-01 20:59 UTC, ocean90 commented on locales/locales.php
> +		$mt->slug = 'mt';
The Google Code is missing, it's `mt`.

2017-07-01 21:02 UTC, ocean90 requested changes

2017-07-01 21:02 UTC, ocean90 commented on locales/locales.php
> +		$mt->slug = 'mt';
The Facebook code is missing, it's `mt_MT`.

2017-07-01 22:22 UTC, tobifjellner commented
Thanks for feedback. Will follow up soon.

2017-07-04 18:39 UTC, ocean90 requested changes

2017-07-04 18:39 UTC, ocean90 commented on locales/locales.php
> +		$mlt->plural_expression = '(n==1 ? 0 : n==0 || ( n%100&gt;1 && n%10010 && n%100&lt;20 ) ? 2 : 3);';
No HTML here, `&gt;` needs to be `>`

2017-07-04 18:39 UTC, ocean90 commented on locales/locales.php
> +		$mlt->plural_expression = '(n==1 ? 0 : n==0 || ( n%100&gt;1 && n%10010 && n%100&lt;20 ) ? 2 : 3);';
There's something missing at `n%10010`

2017-07-04 18:39 UTC, ocean90 commented on locales/locales.php
> +		$mlt = new GP_Locale();
Now that the key is `$mlt`, it needs to be moved after the definition of the `$ml` locale.

2017-07-04 19:45 UTC, tobifjellner commented
Thanks for your feedback. I believe it to be right now, but have also asked the original requester to confirm the plural forms at https://make.wordpress.org/polyglots/2017/06/27/hello-10/#comment-276325

2017-07-11 17:47 UTC, ocean90 requested changes

2017-07-11 17:47 UTC, ocean90 commented on locales/locales.php
> +		$mlt->plural_expression = '(n==1 ? 0 : n==0 || (n%100>=2 && n%100<=10) ? 1 : (n%100>=11 && n%100<=19) ? 2 : 3)';
To make this consistent with other locales, please change `<=19` to `<20`.

2017-07-11 17:47 UTC, ocean90 commented on locales/locales.php
> +		$mlt->google_code = 'mt';
To make this consistent with other locales, please move the Google and Facebook codes to the end of the locale definition.

2017-07-11 18:23 UTC, ocean90 requested changes

2017-07-11 18:23 UTC, ocean90 commented on locales/locales.php
> +		$mlt->google_code = 'mt';
Last request: Google should be before Facebook. 🙈

2017-07-11 19:45 UTC, ocean90 approved these changes

2017-07-11 19:45 UTC, merged