658: Make notices dismissable.
GlotPress/GlotPress-WP pull request #798
Opened 2017-08-16 15:22 UTC by toolstack

Resolves #658.

2017-08-22 18:11 UTC, ocean90 requested changes
What's the source of the icon?

I'd like to see something like WP is using:

```
<button type="button" class="notice-dismiss"><span class="screen-reader-text">Dismiss this notice.</span></button>
```

We don't have a icon font or something similar yet so we either use dashicons or just plain text.

2017-08-22 21:43 UTC, toolstack commented
I grabbed the icon off one of the free icon sites, it was GPL'd, but honestly it was just a placeholder as it kind of look terrible ;)

I considered just not including an icon as the entire notice is "clickable".

We don't have dashicons loaded either so the other option is just plain text like we do on the translation warnings.

2017-08-29 17:24 UTC, ocean90 commented
I see, let's go with plain text then. We can probably just append "Dismiss" to the actual message.

2017-10-08 21:11 UTC, ocean90 approved these changes

2017-10-08 22:52 UTC, merged