790: Improve how untralsated counts are calculated in the tranlsation sets.
GlotPress/GlotPress-WP pull request #799
Opened 2017-08-18 12:17 UTC by toolstack

Resolves #790.

2017-08-22 18:43 UTC, ocean90 requested changes
We also have to invalidate previous caches. See the `if ( ! is_array( $counts ) || ! isset( $counts[0]->total ) ) { // The format was changed in 2.1.` line.

2017-08-22 18:43 UTC, ocean90 commented on gp-includes/things/translation-set.php
> +					o.status = \"+active\" AND
Instead of escaping the quotes we can use single quotes.

2017-08-22 18:43 UTC, ocean90 commented on gp-includes/things/translation-set.php
> +					'hidden'             => 0,
Is there a reason for not counting the hidden originals?

2017-08-22 22:09 UTC, toolstack commented on gp-includes/things/translation-set.php
> +					'hidden'             => 0,
I wasn't sure if you could have a hidden untranslated string, but it would easy to add.

2017-08-22 22:16 UTC, toolstack commented on gp-includes/things/translation-set.php
> +					o.status = \"+active\" AND
:+1:

2017-08-22 22:17 UTC, toolstack commented on gp-includes/things/translation-set.php
> +					'hidden'             => 0,
I've updated the code to return hidden/pubic.

2017-08-22 22:50 UTC, toolstack commented
> We also have to invalidate previous caches. See the if ( ! is_array( $counts ) || ! isset( $counts[0]->total ) ) { // The format was changed in 2.1. line.

Due to how the counts cache is implemented there's no easy way to tell if it needs to be updated without looping through all the entries and looking for the untranslated value, which seems like a big waste for something that will only be used once.

Since the cache will expire on it's own and be replaced with the new values without generating any PHP errors it might be better to live with the untranslated values returning 0 until it does.

We could use the upgrade function to clear the cache entries, but regenerating them all or working with other cache plugins might get complex.

The other option would be to include a version flag in the cache so when we know an upgrade has happened and we should 'expire' the cache.

2017-08-29 17:17 UTC, ocean90 commented
> Due to how the counts cache is implemented

I thought we could just add another `isset()` check but yeah, we don't add the groups if the counts are zero. Maybe we should?

> Since the cache will expire on it's own

No, the cache doesn't have an expiration.

> The other option would be to include a version flag

Instead of adding the flag to the cache value we can also include it in the cache key, like `translation_set_status_breakdown_v2`.

2017-08-29 20:02 UTC, toolstack commented
>> Due to how the counts cache is implemented

> I thought we could just add another isset() check but yeah, we don't add the groups if the counts are zero. Maybe we should?

Considered it, but a version flag seemed better in the long run if we need to make a change that isn't easily detectable via isset().

>>Since the cache will expire on it's own

>No, the cache doesn't have an expiration.

Well, it does when `update_status_breakdown()` gets called :wink:

Until then the old cache values aren't so horrible wrong to necessitate a complete cache flush/rebuild in my opinion.  As soon as anything calls `update_status_breakdown()` the values will be updated.

>>The other option would be to include a version flag

>Instead of adding the flag to the cache value we can also include it in the cache key, like translation_set_status_breakdown_v2.

Could, but then it would be harder to reuse the old values as above (would have to check for two different cache keys).

2017-10-03 11:24 UTC, ocean90 approved these changes

2017-10-03 11:24 UTC, merged