828: Add 7 locales for wordpress.org
GlotPress/GlotPress-WP pull request #832
Opened 2017-09-29 18:16 UTC by tobifjellner

en_p8 = 'English (Pirate)'
es_us = 'Spanish (US)'
lmo = 'Lombard'
lug = 'Luganda'
pap = 'Papiamento'
skr = 'Saraiki'
ssw = 'Swati'
zul = 'Zulu'

2017-09-29 19:31 UTC, toolstack requested changes

2017-09-29 19:31 UTC, toolstack commented on locales/locales.php
> +		$en_p8->native_name = 'Pirate English';
Native name should be the same as English name in this case.

2017-09-29 19:47 UTC, toolstack approved these changes
👍

2017-09-30 14:05 UTC, ocean90 requested changes

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$en_p8->country_code = 'P8';
There's no such country code, the property should be removed.

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$en_p8->google_code = 'x-pirate';
Where did you find the code? I don't see it on https://cloud.google.com/translate/docs/languages#languages-pbmt.

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$lmo->country_code = 'IT';
Country code should be lowercased.

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$lug->country_code = 'UG';
Country code should be lowercased.

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$pap->country_code = 'CW';
Country code should be lowercased.

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$skr->plural_expression = '(n>1)';
Please change this to `(n > 1)`.

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$zul->plural_expression = '(n>1)';
Please change this to `(n > 1)`.

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$skr->country_code = 'PK';
Country code should be lowercased.

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$ssw->country_code = 'SZ';
Country code should be lowercased.

2017-09-30 14:05 UTC, ocean90 commented on locales/locales.php
> +		$zul->country_code = 'ZA';
Country code should be lowercased.

2017-10-03 14:06 UTC, ocean90 commented
@tobifjellner Please do not trigger builds by adding random commits. We can trigger them manually on Travis.

2017-10-17 17:10 UTC, ocean90 commented
FYI: This is still pending because I'm not a fan of the locale for Pirate. The others are fine so maybe we can remove the Pirate one for now.

2017-10-17 17:24 UTC, danieltj27 commented
I, and some others have backed the Pirate locale and would like to see it makes its way in. Both Google and Facebook have Pirate versions and I think even though it’s not technically ‘real’, it’s a nice touch and I’m sure will get a lot of attention.

Please consider this.

2017-10-17 20:06 UTC, toolstack commented
I'm in favour of being inclusive in this case, we already have Klingon, I don't see any reason to be the arbitrator or what locales can be used with GP.

2017-10-17 20:15 UTC, danieltj27 commented
I understand why @ocean90 may have doubts. I do think it'll be a popular language though with enough people contributing to warrant it. As @toolstack has noted, if there is already Klingon then I'm sure an exception can be made for Pirate. I'll stress again that Facebook supports it too.

Whilst it's a bit of fun, I think it would also make translating fun for those that don't already contribute providing a gateway for more people to get involved.

2017-10-17 20:17 UTC, ocean90 commented
This is more about the data of the locale. The `wp_locale` for example is invalid.

2017-10-17 20:25 UTC, danieltj27 commented
I'd suggest using either `en_PI` or `en_PR` for the locale code. After quickly checking the current list of locales, it seems that `_PI` is completely unique which may serve as the best option for the code (which is the same as Facebook's code).

2017-11-13 19:16 UTC, danieltj27 commented
What's the status of this PR at the moment? What do we need to do to get everything merged in?

If I can help by submitting another PR for this then do let me know as I'm happy to help.

cc: @ocean90 @tobifjellner

2017-11-14 19:43 UTC, ocean90 commented
I'm going to rebase this PR to remove the Pirate locale for now. In a separate issue we can continue discussing the form of the Pirate locale.

2017-11-18 14:48 UTC, ocean90 commented
@petyaraykovska reminded me about "Spanish (US)" which also needs another check.

2018-04-06 09:00 UTC, tobifjellner commented
@ocean90 Are any changes still needed, or can this PR be merged?

2018-04-08 14:06 UTC, ocean90 approved these changes

2018-04-08 14:10 UTC, merged