Add locales ful, nso, pap-aw, pap-cw
GlotPress/GlotPress-WP pull request #887
Opened 2018-04-11 00:47 UTC by tobifjellner

Add locales ful, nso, pap-aw, pap-cw for use outside of WP
Remaining locales from PR 309 ( c-schmitz)

2018-04-14 09:48 UTC, ocean90 requested changes

2018-04-14 09:48 UTC, ocean90 commented on locales/locales.php
> +		$pap_aw->lang_code_iso_639_1 = 'pap';
ISO 639-1 codes are always two letter codes. It's only 2 and 3 here.

2018-04-14 09:48 UTC, ocean90 commented on locales/locales.php
> +		$pap_aw->lang_code_iso_639_2 = 'pap';
The country code is missing. Can you add `$pap_aw->country_code = 'aw'` please? (https://www.ethnologue.com/country/AW)

2018-04-14 09:48 UTC, ocean90 commented on locales/locales.php
> +		$pap_cw->lang_code_iso_639_1 = 'pap';
ISO 639-1 codes are always two letter codes. It's only 2 and 3 here.

2018-04-14 09:48 UTC, ocean90 commented on locales/locales.php
> +		$pap_cw->english_name = 'Papiamento (Curaçao and Bonaire)';
Isn't Curaçao the one we already have in https://github.com/glotpress/GlotPress-WP/blob/9a9bfc2/locales/locales.php#L1656-L1663? See country code. So this locale should probably only for Bonaire which has `BQ` as the country code. Therefore the locale variable is `$pap_bq` with `$pap_bq->country_code = 'bq'`.

2018-04-14 09:48 UTC, ocean90 commented on locales/locales.php
> +		$pap_cw->native_name = 'Papiamentu';
The native name needs to include the country name as well otherwise you can't distinguish them in a language dropdown menu for example.

2018-06-14 15:02 UTC, ocean90 requested changes

2018-06-14 15:02 UTC, ocean90 commented on locales/locales.php
> +		$pap_cw->slug = 'pap-cw';
The `wp_locale` is missing.

2018-06-14 15:02 UTC, ocean90 commented on locales/locales.php
> +		$pap_aw->slug = 'pap-aw';
The `wp_locale` is missing.

2018-10-18 15:09 UTC, toolstack commented
@tobifjellner could you update this PR?  I'd like to include it in the 3.0 release.

2020-04-11 16:08 UTC, ocean90 commented
Closing in favour of #1047, #1048, #1049.

2020-04-11 16:08 UTC, closed without merging