Fix Pirate locale code and slug to character length
GlotPress/GlotPress-WP pull request #894
Opened 2018-05-01 07:31 UTC by danieltj27

Issue #891

> The locale column of the translation set only allows 10 characters. Pirate has 11 with art-xpirate so it only gets stored as art-xpirat.

This fixes the issue by changing the locale code and slug to `xx-pirate` to match the Google locale code instead so it's sorted and not cut off.

2018-05-01 09:18 UTC, danieltj27 commented
I've fixed the conflicts the original PR commit was causing. Hopefully the CI test passes!

2018-05-04 12:33 UTC, ocean90 requested changes

2018-05-04 12:33 UTC, ocean90 commented on locales/locales.php
> +		$pirate->slug = 'xx-pirate';
Only the slug needs to be changed, the WP locale should remain as is.

xx-pirate looks odd, let’s just use pirate.

2018-05-04 12:39 UTC, danieltj27 commented
@ocean90 I've updated the changes so it's just the slug that has changed now 👍

2018-05-04 17:41 UTC, ocean90 approved these changes

2018-05-04 17:43 UTC, merged